lcd:
  scene_change_checktimes: 1 # Check times for scene change
codebook:
  codebook_size: 65536 # Size of the codebook
  feature_num: 512 # Number of local features
  feature_dim: 128 # Dimension of the local features
  multiple_assignment: 1 # Number of assignments per local feature
similarity:
  alpha: 3.0 # Weight of the spatial similarity
  similarity_threshold: 0.0 # Threshold for the similarity matrix
  scene_change_threshold: 0.0 # Threshold for the scene change
  topk_scene: 2 # Threshold for the scene change
svm:
  angle_model_path: "/root/LCD/LCDEngine/CC_COOSAC/svm/snm_test/train_angle_0729.model"
  length_model_path: "/root/LCD/LCDEngine/CC_COOSAC/svm/snm_test/train_len_0729.model"